name: Javascript CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: ./.github/workflows/composite-action
      - name: Check Prettier format
        run: yarn format:check
      - name: Check EsLint issues
        run: yarn lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - uses: ./.github/workflows/composite-action
      - name: Provide permission for execution
        run: chmod +x example/android/gradlew
      - name: Check packages
        run: yarn build
      - name: Check Android build
        run: cd example/android && ./gradlew app:assembleRelease
